### ISSUE TITLE
enabled.json does not seem to enable any mods

### ISSUE THREAD

**Issue by tomnieuwland** [hexlo/terraria-tmodloader-server#1]
Hey,

My `enabled.json` is as follows 
```
[
  "BossChecklist",
  "MagicStorageExtra",
  "RecipeBrowser",
  "CalamityMod",
  "CalamityMusicMod"
]
```

and my docker-compose.yml
```
version: '3.2'
services:
  terraria-tmodloader-server1:
    # Github mirror: ghcr.io/hexlo/terraria-tmodloader-server:latest
    image: hexlo/terraria-tmodloader-server:latest
    container_name: terraria-tmodloader-server1
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - 7782:7777
    volumes:
      - type: bind
        source: ./Worlds
        target: /root/.local/share/Terraria/ModLoader/Worlds/
      - type: bind
        source: ./enabled.json
        target: /root/.local/share/Terraria/ModLoader/Mods/enabled.json
    environment:
      - world=/root/.local/share/Terraria/ModLoader/Worlds/Calamity0.wld
      - autocreate=2
      - worldname=Calamity0
      - difficulty=0
      - motd="test123"
```

When I connect to the server via tModLoader, there are no mods enabled on the server
