### ISSUE TITLE
If I stop and restart the docker container, it generates a new world

### ISSUE THREAD

**Issue by adsads** [hexlo/terraria-tmodloader-server#3]
Here is my docker-compose.

```
version: '3.2'
services:
  terraria-tmodloader-server1:
    # Github mirror: ghcr.io/hexlo/terraria-tmodloader-server:latest
    image: hexlo/terraria-tmodloader-server:latest
    container_name: terraria-tmodloader-server1
    restart: unless-stopped
    stdin_open: true
    tty: true
    ports:
      - 7782:7777
    volumes:
      - type: bind
        source: ./Worlds
        target: /root/.local/share/Terraria/ModLoader/Worlds/
      - type: bind
        source: ./enabled.json
        target: /root/.local/share/Terraria/ModLoader/Mods/enabled.json
    environment:
      - world=/root/.local/share/Terraria/ModLoader/Worlds/Calamity2.wld
      - autocreate=3
      - worldname=Calamity2
      - difficulty=1
      - password=salzfam
      - motd="Welcome to 's server! :)"
```
Here is my worlds folder:

``` 

user@games:~/Worlds$ ls -al
total 44516
drwxr-xr-x 2 root  root      4096 May 14 22:34 .
drwxr-x--- 9 user user 4096 May 14 22:40 ..
-rw-r--r-- 1 root  root    168204 May 14 22:25 Calamity22.twld
-rw-r--r-- 1 root  root  11320526 May 14 22:25 Calamity22.wld
-rw-r--r-- 1 root  root    156738 May 14 22:34 Calamity23.twld
-rw-r--r-- 1 root  root  10681080 May 14 22:34 Calamity23.wld
-rw-r--r-- 1 root  root    172742 May 14 22:14 Calamity2.twld
-rw-r--r-- 1 root  root    172743 May 14 22:14 Calamity2.twld.bak
-rw-r--r-- 1 root  root  11442584 May 14 22:14 Calamity2.wld
-rw-r--r-- 1 root  root  11442584 May 14 22:14 Calamity2.wld.bak
``` 
The world I want it to use is Calamity2, it generated a new one called Calamity23 .
